CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username CITEXT NOT NULL UNIQUE,
  password_hash TEXT,
  rud_balance INTEGER NOT NULL DEFAULT 0,
  equipped_skin TEXT NOT NULL DEFAULT 'default',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE user_sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE best_scores (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  song_id TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, song_id)
);

CREATE TABLE user_inventory (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  ability_id TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, ability_id)
);

CREATE TABLE user_redeemed_codes (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  ability_id TEXT NOT NULL,
  redeemed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, ability_id)
);

CREATE TABLE user_owned_skins (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  skin_id TEXT NOT NULL,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, skin_id)
);
